package med.voll.api.domain.medico;

public enum Especialidad {
    
    CARDIOLOGIA,
    NEUROLOGIA,
    PEDIATRIA,
    ORTOPEDIA,
    DERMATOLOGIA,
    GINECOLOGIA,
    UROLOGIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    PSIQUIATRIA,
    ENDOCRINOLOGIA,
    GASTROENTEROLOGIA,
    HEMATOLOGIA 
}
