export enum Especialidad {
    CARDIOLOGIA = 'CARDIOLOGIA',
    NEUROLOGIA = 'NEUROLOGIA',
    PEDIATRIA = 'PEDIATRIA',
    ORTOPEDIA = 'ORTOPEDIA',
    DERMATOLOGIA = 'DERMATOLOGIA',
    GINECOLOGIA = 'GINECOLOGIA',
    UROLOGIA = 'UROLOGIA',
    OFTALMOLOGIA = 'OFTALMOLOGIA',
    OTORRINOLARINGOLOGIA = 'OTORRINOLARINGOLOGIA',
    PSIQUIATRIA = 'PSIQUIATRIA',
    ENDOCRINOLOGIA = 'ENDOCRINOLOGIA',
    GASTROENTEROLOGIA = 'GASTROENTEROLOGIA',
    HEMATOLOGIA = 'HEMATOLOGIA'
}